# Site Settings
title: Sidnei Weber | A theme for Jekyll
email: youremail@xyz.com
description: Some text about your blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sidneiweber.github.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Sidnei Weber
user_description: Seja bem vindo.
disqus_username: sidneiweber

# Social Media
# Remove the item if you don't need it
github_username: sidneiweber
facebook_username: sidnei.weber
twitter_username: twitter_username
instagram_username: instagram_username
linkedin_username: sidnei-weber-143864169
medium_username: @sidnei.weber

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 12
paginate_path: "/page/:num/"
svg_color: "#ff0a16"

# Plugins
plugins:
  - jemoji
  - jekyll-paginate

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Sobre
    url: /sobre/
  - title: Projetos
    subfolderitems:
      - page: Sistema vendas
        url: /projetos/
      - page: SCP Fácil
        url: /projetos/scp-facil/
      - page: Repositório CVS
        url: /projetos/criar-repositorios-no-servidor-cvs/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
