# Profile information
name: Sidnei Weber
title: Sidnei Weber | Life of Sysadmin
description: 'A rotina de um Sysadmin. Falando sobre tecnologia, linux, aws, scripts e etc''s'
permalink: ':title/'
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://sidneiweber.com.br'
tags:
  - blog
  - jekyll
  - aws
  - linux
  - sysadmin
  - devops
  - shell

# Social
github: sidneiweber
linkedin_username: sidnei-weber-143864169
medium: sidnei.weber

# Contact form
email: sidnei.weber@gmail.com

# Comments
discus-identifier: sidneiweber
site.analytics: : UA-921545-12
# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
