name: Sidnei Weber
title: Sidnei Weber | Life of Sysadmin
description: A rotina de um Sysadmin. Falando sobre tecnologia, linux, aws, scripts e etc's
tags:
  - devops
  - linux
  - sysadmin
  - aws
  - shell
email: sidnei.weber@gmail.com
disqus_username: sidneiweber
show_hero: true
